[mgr]
ratio = [0,2,3]
sort_by="extension"
sort_dir_first=true
show_symlink=true
icon = "nerdfont"


[preview]
image_filter="catmull-rom"

[opener]

edit = [
    { run = '$EDITOR "$@"', block = true, desc = "vim" }
]

open = [
    { run = 'xdg-open "$1"', desc = "Open", for = "linux" }
]

reveal = [
	{ run = 'xdg-open "$(dirname "$1")"', desc = "Reveal", for = "linux" }
]

extract = [
	{ run = 'unar "$@"', desc = "Extract here using unar", for = "unix" }
]

play = [
    { run = 'mpv --profile=low-latency --vo=kitty --vo-kitty-use-shm=yes --really-quiet "$@"', block = true, desc = "Play video in terminal", orphan = false }
]

cursor = [
    { run = 'cursor "$@"', block = false, orphan = true, desc = "Open with cursor" }
]

termvisage = [
    { run = 'termvisage --tui "$@"', block = true, orphan = false, desc = "Vew Image(s) in terminal" }
]

pdf = [
    { run = 'tdf -f true -m 1 "$@"', block = true, orphan = false, desc = "View PDF in terminal" }
]

[open]
rules = [
    # Folder
    { name = "*/", use = [ "edit", "cursor", "open", "termvisage", "reveal" ]},
    # Text
    { mime = "text/*", use = [ "edit", "cursor", "reveal" ] },
    # Image
    { mime = "image/*", use = [ "termvisage", "open", "reveal" ]},
    # Media
    { mime = "{audio,video}/*", use = [ "play", "reveal" ] },
    # Archive
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "extract", "reveal" ] },
    # JSON
    { mime = "application/{json,ndjson}", use = [ "edit", "cursor", "reveal" ] },
    { mime = "*/javascript", use = [ "edit", "cursor", "reveal" ] },
    # Empty file
    { mime = "inode/empty", use = [ "edit", "reveal" ] },
    # PDFs
    { name = "*.pdf", use = ["pdf", "open", "reveal"] },
    # Fallback
    { name = "*", use = [ "open", "reveal" ] }
]

[plugin]

prepend_previewers = [
	# Code
    { mime = "text/*", run = 'piper -- batcat --color=always --paging=never --style=plain "$1"' },
    { mime = "application/{mbox,javascript,wine-extension-ini}", run = 'piper -- batcat --color=always --paging=never --style=plain "$1"' },
	# JSON
    { mime = "application/{json,ndjson}", run = 'piper -- batcat --color=always --paging=never --style=plain "$1"' },

    # Audio Preview exiftools
    { mime = "audio/*",   run = "exifaudio"},

    ]

prepend_fetchers = [
    
    { id = "git", name = "*", run = "git", prio = "normal" },
    { id = "git", name = "*/", run = "git", prio = "normal" },

]

